# Generated by Django 2.1 on 2018-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapathon',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mapathon',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
