# Generated by Django 2.1 on 2018-08-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180805_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('mapathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.Mapathon')),
            ],
        ),
    ]
